services:
  - type: web
    name: Leak-Txt-Uploader-Working
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/I-Devil-69/Leak-Txt-Uploader-Working
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_NAME
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: MONGO_URI
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8781  # Default port value, update if needed
